// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8M42TpW7aIstNXJMM3WgXUo_wQgHMqw',
    appId: '1:847680018818:android:78003371afd055b0fd579b',
    messagingSenderId: '847680018818',
    projectId: 'auth-news-app-537da',
    storageBucket: 'auth-news-app-537da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkld7LxgM1t9rmVU9l_xoTAqaN__r8aak',
    appId: '1:847680018818:ios:a73376148033127ffd579b',
    messagingSenderId: '847680018818',
    projectId: 'auth-news-app-537da',
    storageBucket: 'auth-news-app-537da.appspot.com',
    androidClientId: '847680018818-9mbok4ujokn30h1qtkpoeqtekoc6m75s.apps.googleusercontent.com',
    iosClientId: '847680018818-f3fh107093ees6s3djccp0t4k9r1lro4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
